name: Build Resume PDF and Website

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
      
      - name: Install Python dependencies
        run: |
          pip install pybtex
      
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex
          working_directory: .
          compiler: pdflatex
          args: -file-line-error -halt-on-error -interaction=nonstopmode -output-directory=build
          post_compile: |
            bibtex build/publications.aux
            pdflatex -file-line-error -halt-on-error -interaction=nonstopmode -output-directory=build resume.tex
            pdflatex -file-line-error -halt-on-error -interaction=nonstopmode -output-directory=build resume.tex
            mv build/resume.pdf .
          extra_system_packages: "biber"
      
      - name: Build website
        run: |
          cd website
          bash build.sh
      
      - name: Copy resume to website
        run: cp resume.pdf website/
      
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: resume-pdf
          path: resume.pdf
          retention-days: 90
      
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: website/
      
      - name: Commit and push PDF and website (if on master/main)
        if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main')
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add resume.pdf website/publications_generated.html website/blog_index.json
          git add website/blog/*.html 2>/dev/null || true
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update resume and website [skip ci]"
          git push

  deploy:
    needs: build
    if: github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
